from lista_linear import ListaLinearContigua

lista = ListaLinearContigua(5)

lista.inserir(1,1)
lista.inserir(2,2)
lista.inserir(3,3)
lista.inserir(4,4)
lista.inserir(5,5)
lista.remover(1)
lista.remover(2)
lista.remover(3)
lista.remover(2)
lista.remover(1)
lista.inserir(1,1)
lista.inserir(2,2)
lista.inserir(3,3)
lista.inserir(4,4)
lista.inserir(5,5)
lista.exibir()
lista.remover(2)
lista.exibir()
lista.remover(3)
lista.exibir()
print(lista.consultar(2))